# Generated by Django 3.1.4 on 2020-12-15 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Application', '0003_auto_20201215_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='productid',
            name='userid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Application.customerproduct'),
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='User',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
