# Generated by Django 3.1.4 on 2020-12-15 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Application', '0005_auto_20201215_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproduct',
            name='ProductID',
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='User',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='customerid',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Application.productid'),
        ),
    ]
