# Generated by Django 3.1.4 on 2020-12-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_auto_20201216_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.CharField(max_length=200)),
            ],
        ),
    ]
