# Generated by Django 3.1.4 on 2020-12-15 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_auto_20201216_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='customerid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Application.productid'),
        ),
    ]
