# Generated by Django 3.1.4 on 2020-12-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_auto_20201216_0046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
