# Generated by Django 3.1.4 on 2020-12-15 20:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Application', '0013_delete_car'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerProduct',
            new_name='CustomerProd',
        ),
    ]
