# Generated by Django 3.1.4 on 2020-12-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0015_image_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='coverimage',
        ),
        migrations.AddField(
            model_name='pdf',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
