# Generated by Django 3.1.7 on 2021-03-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0018_facename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagestore',
            field=models.FileField(null=True, upload_to='abc/'),
        ),
    ]
