# Generated by Django 3.1.7 on 2021-05-05 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Application', '0019_auto_20210307_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='facename',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='imagestore',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
